server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/coolshare_db?useSSL=false&serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  session:
    store-type: jdbc
