server:
  port=80
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/coolshare_db?characterEncoding=UTF-8  # ?????URL
    username: root # ??????
    password: 123456  # ?????
    driver-class-name: com.mysql.jdbc.Driver  # ???????
